/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      colors: {
        background: "#0e1321",
        "on-background": "#dee2f6",
        surface: "#0e1321",
        "surface-dim": "#0e1321",
        "surface-bright": "#343948",
        "surface-container": "#1a1f2e",
        "surface-container-low": "#161b2a",
        "surface-container-lowest": "#090e1c",
        "surface-container-high": "#252a39",
        "surface-container-highest": "#303444",
        "surface-variant": "#303444",
        "on-surface": "#dee2f6",
        "on-surface-variant": "#d0c5af",
        primary: "#f2ca50",
        "on-primary": "#3c2f00",
        "primary-container": "#d4af37",
        "on-primary-container": "#554300",
        "primary-fixed": "#ffe088",
        "primary-fixed-dim": "#e9c349",
        secondary: "#a0cde4",
        "on-secondary": "#003547",
        "secondary-container": "#204e62",
        "on-secondary-container": "#92bfd6",
        "secondary-fixed": "#bfe9ff",
        "secondary-fixed-dim": "#a0cde4",
        tertiary: "#e3cba8",
        "on-tertiary": "#3c2e15",
        "tertiary-container": "#c6b08e",
        "on-tertiary-container": "#524328",
        "tertiary-fixed": "#f7dfbb",
        "tertiary-fixed-dim": "#dac3a0",
        outline: "#99907c",
        "outline-variant": "#4d4635",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#dee2f6",
        "inverse-on-surface": "#2b303f",
        "inverse-primary": "#735c00",
        border: "#4d4635",
        muted: "#252a39",
        "muted-foreground": "#99907c",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        heading: ["'Bricolage Grotesque'", "sans-serif"],
        body: ["'Inter'", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
        stamp: ["'Special Elite'", "monospace"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "label-sm": ["13px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "700" }],
      },
      spacing: {
        "margin-desktop": "48px",
        "margin-mobile": "16px",
        gutter: "24px",
        "container-max": "1200px",
      },
      animation: {
        "fade-in": "fadeIn 0.3s ease-out",
        "slide-up": "slideUp 0.4s ease-out",
        "hover-lift": "hoverLift 0.3s ease-out",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [
    require("@tailwindcss/typography"),
  ],
};
